Numpy Library in python
Faster than list data structures

In [2]:
import numpy as np;   #to import the numpy

In [3]:
#to create a array in list
lst1=[i for i in range(100)]
print(lst1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [7]:
#to create a array in numpy
lst2=np.array([i for i in range(100)])
print(lst2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


to find its type u can use type function
numpy.ndarray means n dimensional array

u can also find its shape which shows rows and columns

In [11]:
type(lst2)


numpy.ndarray

In [10]:
lst2.shape

(100,)

to create a multidimensional array
the syntax is very much important 

In [15]:
lst3=np.array([(1,23,4,5),(2,4,9,8)])
print(lst3)
lst3.shape

[[ 1 23  4  5]
 [ 2  4  9  8]]


(2, 4)

now placeholders
to start with zeroes,ones and with a specific no

In [18]:
x=np.zeros((2,3))
y=np.ones((6,6));
print(x)
print(y) 

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


for a specific no

In [19]:
z=np.full((3,4),88)
print(z)

[[88 88 88 88]
 [88 88 88 88]
 [88 88 88 88]]


to create a identity matrix

In [21]:
identitymatrix=np.eye(5)
print(identitymatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


also used for random values
random.random --> values will be between 0 to 1   
two arguments only row and column inside double brackets

random.randint --> values will be integer and 
contains four arguments limits also 
dimensions inside double brackets

linspace(lowerlimit,upperlimit,how many numbers we want)  --> evenly spaced no

In [23]:
a=np.random.random((3,4))
print(a)

[[0.08990132 0.04105322 0.61180413 0.31801526]
 [0.65608367 0.51063768 0.33294871 0.58112912]
 [0.79880146 0.94155322 0.76069464 0.29566886]]


In [25]:
b=np.random.randint(10,110,(3,5))
print(b)

[[106  81  13  70  91]
 [ 90  93 106  60  51]
 [ 21  72  28  25  10]]


In [27]:
c=np.linspace(10,110,10)
print(c)

[ 10.          21.11111111  32.22222222  43.33333333  54.44444444
  65.55555556  76.66666667  87.77777778  98.88888889 110.        ]


if the steps are decided then np.array(lowerlimit,upperlimit,space/steps)

In [32]:
d=np.array(10,100,3)
print(d)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

to convert a list into array

In [40]:
lst4=np.array(lst1)
print(lst4)
type(lst1)
type(lst4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


numpy.ndarray

Analysing an array
a.shape tells the dimensions
a.ndim tell how many dimensions
a.size tell how many elements
a.dtype tells the data type

In [41]:
a=np.random.randint(10,100,(5,5))
print(a)

[[88 20 10 31 74]
 [10 77 65 78 18]
 [33 30 75 69 34]
 [50 23 62 12 48]
 [77 53 14 99 49]]


In [44]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)


(5, 5)
2
25
int32


Mathematical operation
we can perform it like mathematical operation

In [47]:
a=np.random.randint(10,100,(5,5))
print(a)
b=np.random.randint(10,100,(5,5))
print(b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[39 33 83 43 20]
 [60 95 17 33 78]
 [70 27 41 96 71]
 [71 80 25 39 88]
 [60 60 67 41 71]]
[[13 25 40 91 53]
 [65 29 96 51 63]
 [33 50 90 28 35]
 [23 70 66 28 94]
 [56 12 80 10 72]]
[[ 52  58 123 134  73]
 [125 124 113  84 141]
 [103  77 131 124 106]
 [ 94 150  91  67 182]
 [116  72 147  51 143]]
[[ 26   8  43 -48 -33]
 [ -5  66 -79 -18  15]
 [ 37 -23 -49  68  36]
 [ 48  10 -41  11  -6]
 [  4  48 -13  31  -1]]
[[ 507  825 3320 3913 1060]
 [3900 2755 1632 1683 4914]
 [2310 1350 3690 2688 2485]
 [1633 5600 1650 1092 8272]
 [3360  720 5360  410 5112]]
[[3.         1.32       2.075      0.47252747 0.37735849]
 [0.92307692 3.27586207 0.17708333 0.64705882 1.23809524]
 [2.12121212 0.54       0.45555556 3.42857143 2.02857143]
 [3.08695652 1.14285714 0.37878788 1.39285714 0.93617021]
 [1.07142857 5.         0.8375     4.1        0.98611111]]


Manipulation of array

In [48]:
transpose_a=np.transpose(a)
print(a)
print(transpose_a)

[[39 33 83 43 20]
 [60 95 17 33 78]
 [70 27 41 96 71]
 [71 80 25 39 88]
 [60 60 67 41 71]]
[[39 60 70 71 60]
 [33 95 27 80 60]
 [83 17 41 25 67]
 [43 33 96 39 41]
 [20 78 71 88 71]]


Reshaping an array --> to change the dimension of an array

In [50]:
a=np.random.randint(34,55,(4,4))
print(a)
b=a.reshape((8,2))
print(b)

[[37 46 35 53]
 [50 36 50 47]
 [47 49 42 54]
 [50 34 35 49]]
[[37 46]
 [35 53]
 [50 36]
 [50 47]
 [47 49]
 [42 54]
 [50 34]
 [35 49]]
